-- IELTS prep schema. JSON documents are stored as text (varchar up to 1M chars in H2) and mapped to
-- Java records by the services, so the schema stays portable.

create table app_users (
    id              bigint generated by default as identity primary key,
    email           varchar(255) not null unique,
    password_hash   varchar(255) not null,
    role            varchar(32)  not null,
    created_at      timestamp with time zone not null,
    last_login_at   timestamp with time zone
);

create table user_settings (
    id                          bigint primary key,
    exam_type                   varchar(16)  not null,
    current_band                decimal(3,1) not null,
    target_band                 decimal(3,1) not null,
    test_date                   date,
    audio_mode                  varchar(16)  not null,
    speech_rate                 double precision not null default 1.0,
    listening_reading_seconds   int not null default 30,
    listening_transfer_minutes  int not null default 10,
    daily_study_minutes         int not null default 90,
    resolved_after_pieces       int not null default 5,
    onboarding_done             boolean not null default false,
    updated_at                  timestamp with time zone not null
);

create table items (
    id                   bigint generated by default as identity primary key,
    module               varchar(16)  not null,
    task_type            varchar(48)  not null,
    variant              varchar(64),
    question_types       varchar(512),
    exam_type            varchar(16)  not null,
    difficulty           int,
    cefr                 varchar(8),
    topic                varchar(255),
    title                varchar(512),
    source_url           varchar(1024),
    licence              varchar(255),
    content              varchar(1000000) not null,
    answer_key           varchar(1000000),
    verification_status  varchar(16)  not null,
    verification_notes   varchar(1000000),
    generation_attempts  int not null default 0,
    origin               varchar(16)  not null,
    seed_key             varchar(255) unique,
    times_served         int not null default 0,
    last_served_at       timestamp with time zone,
    created_at           timestamp with time zone not null
);
create index idx_items_bucket on items (task_type, variant, verification_status, times_served);

create table sessions (
    id                   bigint generated by default as identity primary key,
    module               varchar(16) not null,
    mode                 varchar(16) not null,
    kind                 varchar(48) not null,
    mock_test_id         bigint,
    item_ids             varchar(1024),
    started_at           timestamp with time zone not null,
    finished_at          timestamp with time zone,
    time_limit_seconds   int,
    time_used_seconds    int,
    raw_score            int,
    max_score            int,
    band_estimate        decimal(3,1),
    status               varchar(16) not null
);
create index idx_sessions_module on sessions (module, started_at);

create table attempts (
    id                    bigint generated by default as identity primary key,
    session_id            bigint not null references sessions (id),
    item_id               bigint references items (id),
    module                varchar(16) not null,
    task_type             varchar(48) not null,
    my_answers            varchar(1000000),
    raw_score             int,
    max_score             int,
    band_estimate         decimal(3,1),
    per_criterion_bands   varchar(4000),
    per_question          varchar(1000000),
    feedback              varchar(1000000),
    duration_seconds      int,
    word_count            int,
    status                varchar(24) not null,
    submitted_at          timestamp with time zone not null,
    graded_at             timestamp with time zone
);
create index idx_attempts_module on attempts (module, submitted_at);
create index idx_attempts_session on attempts (session_id);

create table errors (
    id                bigint generated by default as identity primary key,
    attempt_id        bigint not null references attempts (id),
    module            varchar(16) not null,
    type              varchar(16) not null,
    subtype           varchar(64) not null,
    grammar_area      varchar(48),
    original          varchar(4000) not null,
    correction        varchar(4000),
    explanation       varchar(4000),
    created_at        timestamp with time zone not null,
    resolved_at       timestamp with time zone,
    drill_count       int not null default 0,
    last_drilled_at   timestamp with time zone
);
create index idx_errors_subtype on errors (type, subtype, created_at);

create table grammar_progress (
    id                   bigint generated by default as identity primary key,
    area                 varchar(48) not null unique,
    proficiency          double precision not null default 0,
    diagnostic_score     double precision,
    last_tested          timestamp with time zone,
    drills_done          int not null default 0,
    questions_answered   int not null default 0,
    correct_answers      int not null default 0,
    accuracy             double precision not null default 0,
    lesson_viewed_at     timestamp with time zone
);

create table grammar_diagnostics (
    id            bigint generated by default as identity primary key,
    status        varchar(16) not null,
    state         varchar(1000000) not null,
    started_at    timestamp with time zone not null,
    finished_at   timestamp with time zone
);

create table vocab_cards (
    id                  bigint generated by default as identity primary key,
    word                varchar(128) not null unique,
    part_of_speech      varchar(32),
    definition          varchar(2000),
    examples            varchar(8000),
    collocations        varchar(4000),
    awl_sublist         int,
    cefr                varchar(8),
    topic               varchar(64),
    source              varchar(32) not null,
    source_ref          varchar(255),
    context_sentence    varchar(2000),
    ease_factor         double precision not null default 2.5,
    interval_days       int not null default 0,
    repetitions         int not null default 0,
    lapses              int not null default 0,
    due_at              timestamp with time zone not null,
    last_reviewed_at    timestamp with time zone,
    enrichment_status   varchar(16) not null,
    suspended           boolean not null default false,
    created_at          timestamp with time zone not null
);
create index idx_vocab_due on vocab_cards (suspended, due_at);

create table vocab_reviews (
    id                   bigint generated by default as identity primary key,
    card_id              bigint not null references vocab_cards (id) on delete cascade,
    grade                int not null,
    interval_days_after  int not null,
    reviewed_at          timestamp with time zone not null
);

create table api_usage (
    id                  bigint generated by default as identity primary key,
    model               varchar(64) not null,
    purpose             varchar(32) not null,
    input_tokens        int not null default 0,
    output_tokens       int not null default 0,
    cache_read_tokens   int not null default 0,
    cache_write_tokens  int not null default 0,
    cost_usd            decimal(12,6) not null default 0,
    batch               boolean not null default false,
    success             boolean not null,
    error               varchar(2000),
    duration_ms         int,
    ref                 varchar(255),
    created_at          timestamp with time zone not null
);
create index idx_api_usage_created on api_usage (created_at);

create table study_plan (
    id           bigint generated by default as identity primary key,
    plan_date    date not null,
    module       varchar(16) not null,
    task         varchar(255) not null,
    details      varchar(2000),
    task_type    varchar(48),
    variant      varchar(64),
    minutes      int not null default 30,
    priority     int not null default 2,
    done         boolean not null default false,
    done_at      timestamp with time zone,
    source       varchar(16) not null,
    week_start   date,
    created_at   timestamp with time zone not null
);
create index idx_study_plan_date on study_plan (plan_date);

create table coach_reports (
    id           bigint generated by default as identity primary key,
    week_start   date not null,
    week_end     date not null,
    report       varchar(1000000) not null,
    stats        varchar(1000000),
    trigger_type varchar(16) not null,
    created_at   timestamp with time zone not null
);

create table mock_tests (
    id                     bigint generated by default as identity primary key,
    status                 varchar(16) not null,
    stage                  varchar(16) not null,
    listening_session_id   bigint,
    reading_session_id     bigint,
    writing_session_id     bigint,
    speaking_session_id    bigint,
    listening_band         decimal(3,1),
    reading_band           decimal(3,1),
    writing_band           decimal(3,1),
    speaking_band          decimal(3,1),
    overall_band           decimal(3,1),
    report                 varchar(1000000),
    started_at             timestamp with time zone not null,
    finished_at            timestamp with time zone
);

create table topic_usage (
    topic         varchar(64) primary key,
    times_used    int not null default 0,
    last_used_at  timestamp with time zone
);

create table batch_jobs (
    id                  bigint generated by default as identity primary key,
    anthropic_batch_id  varchar(128) not null,
    stage               varchar(16) not null,
    task_type           varchar(48) not null,
    request_count       int not null,
    status              varchar(16) not null,
    details             varchar(1000000),
    created_at          timestamp with time zone not null,
    finished_at         timestamp with time zone
);

create table speaking_responses (
    id                 bigint generated by default as identity primary key,
    session_id         bigint not null references sessions (id),
    attempt_id         bigint references attempts (id),
    part               int not null,
    question_index     int not null,
    question           varchar(2000) not null,
    audio_path         varchar(1024),
    transcript         varchar(20000),
    duration_seconds   int,
    created_at         timestamp with time zone not null
);
create index idx_speaking_session on speaking_responses (session_id);
