-- Week-level study plan metadata (phase, focus note, who wrote it) and the author of each coach report.
create table plan_meta (
    id            bigint generated by default as identity primary key,
    start_date    date not null,
    end_date      date not null,
    phase         varchar(16) not null,
    focus         varchar(4000),
    source        varchar(16) not null,
    generated_at  timestamp with time zone not null
);

alter table coach_reports add column generated_by varchar(16) default 'AI' not null;
