package com.ieltsprep.plan;

import com.ieltsprep.claude.ClaudeCall;
import com.ieltsprep.claude.ClaudeService;
import com.ieltsprep.coach.CoachReportContent;
import com.ieltsprep.coach.CoachReportRepository;
import com.ieltsprep.common.ApiException;
import com.ieltsprep.common.Json;
import com.ieltsprep.dashboard.DashboardDtos.CriteriaPoint;
import com.ieltsprep.dashboard.DashboardDtos.DashboardView;
import com.ieltsprep.dashboard.DashboardService;
import com.ieltsprep.grammar.GrammarDtos;
import com.ieltsprep.grammar.GrammarService;
import com.ieltsprep.grammar.GrammarTaxonomy;
import com.ieltsprep.plan.PlanGenerator.Draft;
import com.ieltsprep.plan.PlanGenerator.Result;
import com.ieltsprep.session.PracticeSession;
import com.ieltsprep.session.PracticeSessionRepository;
import com.ieltsprep.session.SessionKind;
import com.ieltsprep.session.SessionStatus;
import com.ieltsprep.settings.SettingsService;
import com.ieltsprep.settings.UserSettings;
import com.ieltsprep.vocab.VocabCardRepository;
import com.ieltsprep.vocab.VocabReviewRepository;
import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.stream.Collectors;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.support.TransactionTemplate;

/**
 * The rolling seven-day study plan: generated by {@link PlanGenerator} when days are missing, optionally personalised
 * by Claude (study-plan prompt) on request and after each weekly coach report, and ticked off automatically when a
 * matching practice session is completed that day.
 */
@Service
public class PlanService {

    private static final Logger log = LoggerFactory.getLogger(PlanService.class);
    static final int DAYS = 7;

    record AiPlan(String focus, List<AiDay> days) {
        record AiDay(String date, List<AiTask> tasks) {}

        record AiTask(String action, String variant, String title, String why, Integer minutes) {}
    }

    private final PlanTaskRepository tasks;
    private final PlanMetaRepository metas;
    private final SettingsService settings;
    private final DashboardService dashboard;
    private final GrammarService grammar;
    private final GrammarTaxonomy taxonomy;
    private final VocabCardRepository vocabCards;
    private final VocabReviewRepository vocabReviews;
    private final PracticeSessionRepository sessions;
    private final CoachReportRepository coachReports;
    private final ClaudeService claude;
    private final TransactionTemplate tx;
    private final Clock clock;

    public PlanService(PlanTaskRepository tasks, PlanMetaRepository metas, SettingsService settings, DashboardService dashboard,
            GrammarService grammar, GrammarTaxonomy taxonomy, VocabCardRepository vocabCards, VocabReviewRepository vocabReviews,
            PracticeSessionRepository sessions, CoachReportRepository coachReports, ClaudeService claude, TransactionTemplate tx,
            Clock clock) {
        this.tasks = tasks;
        this.metas = metas;
        this.settings = settings;
        this.dashboard = dashboard;
        this.grammar = grammar;
        this.taxonomy = taxonomy;
        this.vocabCards = vocabCards;
        this.vocabReviews = vocabReviews;
        this.sessions = sessions;
        this.coachReports = coachReports;
        this.claude = claude;
        this.tx = tx;
        this.clock = clock;
    }

    // ------------------------------------------------------------------ reading the plan

    @Transactional
    public PlanDtos.PlanView view() {
        LocalDate today = LocalDate.now(clock);
        ensure(today);
        autoComplete(today);
        List<PlanTask> window = tasks.findByPlanDateBetweenOrderByPlanDateAscPriorityAscIdAsc(today, today.plusDays(DAYS - 1));
        Map<LocalDate, List<PlanTask>> byDate = new TreeMap<>(window.stream().collect(Collectors.groupingBy(PlanTask::getPlanDate)));
        LocalDate testDate = settings.get().getTestDate();
        List<PlanDtos.DayView> days = new ArrayList<>();
        for (int i = 0; i < DAYS; i++) {
            LocalDate d = today.plusDays(i);
            List<PlanTask> list = byDate.getOrDefault(d, List.of());
            days.add(new PlanDtos.DayView(d, i == 0, d.equals(testDate), list.stream().mapToInt(PlanTask::getMinutes).sum(),
                    list.stream().filter(PlanTask::isDone).mapToInt(PlanTask::getMinutes).sum(), list.stream().map(PlanService::view).toList()));
        }
        Integer dtt = testDate == null ? null : (int) ChronoUnit.DAYS.between(today, testDate);
        PlanGenerator.Phase phase = PlanGenerator.phase(dtt);
        PlanMeta meta = metas.findFirstByOrderByGeneratedAtDescIdDesc().orElse(null);
        return new PlanDtos.PlanView(today, testDate, dtt, phase.name(), phase.label(), meta == null ? null : meta.getFocus(),
                meta == null ? "RULES" : meta.getSource(), meta == null ? null : meta.getGeneratedAt(), claude.isAvailable(), days);
    }

    @Transactional
    public PlanDtos.TaskView toggle(long id, boolean done) {
        PlanTask t = tasks.findById(id).orElseThrow(() -> ApiException.notFound("Plan task " + id));
        t.setDone(done);
        t.setDoneAt(done ? Instant.now(clock) : null);
        return view(t);
    }

    static PlanDtos.TaskView view(PlanTask t) {
        return new PlanDtos.TaskView(t.getId(), t.getPlanDate(), t.getModule(), t.getAction(), t.getVariant(), t.getTask(), t.getDetails(),
                t.getMinutes(), t.getPriority(), t.isDone(), t.getDoneAt());
    }

    /** Fills in any missing days of the rolling window with the rule-based planner. */
    void ensure(LocalDate today) {
        LocalDate firstMissing = null;
        for (int i = 0; i < DAYS; i++) {
            if (!tasks.existsByPlanDate(today.plusDays(i))) {
                firstMissing = today.plusDays(i);
                break;
            }
        }
        if (firstMissing == null) {
            return;
        }
        int days = (int) ChronoUnit.DAYS.between(firstMissing, today.plusDays(DAYS));
        Result draft = PlanGenerator.generate(inputs(today), firstMissing, days);
        store(firstMissing, draft.tasks(), "RULES");
        saveMeta(firstMissing, days, draft.phase(), draft.focus(), "RULES");
    }

    // ------------------------------------------------------------------ regeneration

    /** Rebuilds the next seven days (keeping tasks already done). With {@code ai}, Claude personalises the draft. */
    public PlanDtos.PlanView regenerate(boolean ai) {
        regenerate(ai, false);
        return view();
    }

    public void regenerate(boolean ai, boolean background) {
        LocalDate today = LocalDate.now(clock);
        PlanInputs in = inputs(today);
        Result draft = PlanGenerator.generate(in, today, DAYS);
        List<Draft> plan = draft.tasks();
        String focus = draft.focus();
        String source = "RULES";
        if (ai && claude.isAvailable()) {
            try {
                AiPlan refined = callClaude(in, draft, today, background);
                plan = merge(draft, refined, in);
                focus = refined.focus() == null || refined.focus().isBlank() ? focus : refined.focus();
                source = "AI";
            } catch (RuntimeException e) {
                log.warn("Study plan personalisation failed, keeping the rule-based plan: {}", e.getMessage());
            }
        }
        List<Draft> finalPlan = plan;
        String finalFocus = focus;
        String finalSource = source;
        tx.executeWithoutResult(s -> {
            tasks.deleteAll(tasks.findByPlanDateGreaterThanEqual(today).stream().filter(t -> !t.isDone()).toList());
            store(today, finalPlan, finalSource);
            saveMeta(today, DAYS, draft.phase(), finalFocus, finalSource);
        });
    }

    private AiPlan callClaude(PlanInputs in, Result draft, LocalDate from, boolean background) {
        Integer dtt = PlanGenerator.daysToTest(in, from);
        Map<String, Object> vars = new HashMap<>();
        vars.put("from", from.toString());
        vars.put("to", from.plusDays(DAYS - 1).toString());
        vars.put("phase", draft.phase().label());
        vars.put("days_to_test", dtt == null ? "unknown" : String.valueOf(dtt));
        vars.put("daily_minutes", String.valueOf(in.dailyMinutes()));
        vars.put("profile", Json.pretty(in));
        vars.put("priorities", in.coachPriorities().isEmpty() ? "(no coach report yet)" : "- " + String.join("\n- ", in.coachPriorities()));
        vars.put("draft", Json.pretty(draftJson(draft)));
        ClaudeCall<AiPlan> call = ClaudeCall.of("study-plan", vars, AiPlan.class).ref("study plan " + from);
        return claude.call(background ? call.inBackground() : call);
    }

    static List<Map<String, Object>> draftJson(Result draft) {
        Map<LocalDate, List<Draft>> byDate = new TreeMap<>(draft.tasks().stream().collect(Collectors.groupingBy(Draft::date)));
        List<Map<String, Object>> days = new ArrayList<>();
        byDate.forEach((d, list) -> {
            Map<String, Object> day = new LinkedHashMap<>();
            day.put("date", d.toString());
            day.put("weekday", d.getDayOfWeek().toString());
            day.put("tasks", list.stream().map(t -> {
                Map<String, Object> m = new LinkedHashMap<>();
                m.put("action", t.action().name());
                m.put("variant", t.variant() == null ? "" : t.variant());
                m.put("title", t.title());
                m.put("why", t.why());
                m.put("minutes", t.minutes());
                return m;
            }).toList());
            days.add(day);
        });
        return days;
    }

    /**
     * Validates Claude's plan against the draft: unknown dates, actions or variants are dropped; locked days (mock test,
     * rest, the test and the day before) and days Claude left out keep the draft; every day keeps a vocabulary review.
     */
    List<Draft> merge(Result draft, AiPlan ai, PlanInputs in) {
        Map<LocalDate, List<Draft>> base = new TreeMap<>(draft.tasks().stream().collect(Collectors.groupingBy(Draft::date)));
        Map<LocalDate, List<Draft>> proposed = new HashMap<>();
        for (AiPlan.AiDay day : ai.days() == null ? List.<AiPlan.AiDay>of() : ai.days()) {
            LocalDate d;
            try {
                d = LocalDate.parse(day.date());
            } catch (RuntimeException e) {
                continue;
            }
            if (!base.containsKey(d) || day.tasks() == null) {
                continue;
            }
            List<Draft> list = new ArrayList<>();
            for (AiPlan.AiTask t : day.tasks()) {
                Draft ok = validate(d, t, in);
                if (ok != null) {
                    list.add(ok);
                }
            }
            proposed.put(d, list);
        }
        int budget = Math.max(30, Math.min(300, in.dailyMinutes()));
        List<Draft> out = new ArrayList<>();
        base.forEach((d, draftDay) -> {
            boolean locked = draftDay.stream().anyMatch(t -> t.action() == PlanAction.MOCK_TEST || t.action() == PlanAction.REST);
            List<Draft> mine = proposed.get(d);
            boolean usable = !locked && mine != null && mine.stream().anyMatch(t -> isPractice(t.action()));
            List<Draft> day = usable ? new ArrayList<>(mine) : new ArrayList<>(draftDay);
            if (usable) {
                day.removeIf(t -> t.action() == PlanAction.MOCK_TEST || t.action() == PlanAction.REST);
                long vocab = day.stream().filter(t -> t.action() == PlanAction.VOCAB_REVIEW).count();
                if (vocab == 0) {
                    draftDay.stream().filter(t -> t.action() == PlanAction.VOCAB_REVIEW).findFirst().ifPresent(day::add);
                } else if (vocab > 1) {
                    boolean[] kept = {false};
                    day.removeIf(t -> {
                        if (t.action() != PlanAction.VOCAB_REVIEW) {
                            return false;
                        }
                        if (!kept[0]) {
                            kept[0] = true;
                            return false;
                        }
                        return true;
                    });
                }
                day.sort(Comparator.comparingInt(Draft::priority));
                int limit = (int) Math.round(budget * 1.4);
                while (day.stream().mapToInt(Draft::minutes).sum() > limit && day.stream().filter(t -> isPractice(t.action())).count() > 1) {
                    Draft last = day.stream().filter(t -> isPractice(t.action())).reduce((a, b) -> b).orElseThrow();
                    day.remove(last);
                }
            }
            out.addAll(day);
        });
        return out;
    }

    private Draft validate(LocalDate d, AiPlan.AiTask t, PlanInputs in) {
        PlanAction action;
        try {
            action = PlanAction.valueOf(t.action());
        } catch (RuntimeException e) {
            return null;
        }
        if (action == PlanAction.MOCK_TEST || action == PlanAction.REST) {
            return null;
        }
        String v = t.variant() == null ? "" : t.variant().trim();
        String variant = switch (action) {
            case READING_PASSAGE -> Set.of("1", "2", "3").contains(v) ? v : "3";
            case LISTENING_SECTION -> Set.of("1", "2", "3", "4").contains(v) ? v : "4";
            case SPEAKING_PART -> Set.of("PART1", "PART2", "PART3").contains(v) ? v : "PART2";
            case GRAMMAR_AREA -> taxonomy.area(v).isPresent() ? v : null;
            case GRAMMAR_ERRORS -> taxonomy.isKnownSubtype("grammar", v) ? GrammarTaxonomy.normalise(v) : null;
            default -> "";
        };
        if (variant == null) {
            return null;
        }
        int minutes = t.minutes() == null ? action.defaultMinutes() : Math.max(5, Math.min(120, t.minutes()));
        String title = t.title() == null || t.title().isBlank() ? PlanGenerator.humanise(action.name()) : cut(t.title(), 255);
        return new Draft(d, action, variant.isEmpty() ? null : variant, title, cut(t.why(), 2000), minutes, priority(action));
    }

    static boolean isPractice(PlanAction a) {
        return !Set.of(PlanAction.VOCAB_REVIEW, PlanAction.REST, PlanAction.REVIEW_MISTAKES, PlanAction.GRAMMAR_AREA,
                PlanAction.GRAMMAR_ERRORS, PlanAction.GRAMMAR_DIAGNOSTIC).contains(a);
    }

    static int priority(PlanAction a) {
        return switch (a) {
            case VOCAB_REVIEW -> 3;
            case GRAMMAR_AREA, GRAMMAR_ERRORS, REVIEW_MISTAKES -> 2;
            default -> 1;
        };
    }

    private void store(LocalDate from, List<Draft> drafts, String source) {
        Map<LocalDate, Set<String>> doneByDate = new HashMap<>();
        tasks.findByPlanDateGreaterThanEqual(from).stream().filter(PlanTask::isDone)
                .forEach(t -> doneByDate.computeIfAbsent(t.getPlanDate(), k -> new HashSet<>()).add(t.getAction()));
        Instant now = Instant.now(clock);
        for (Draft d : drafts) {
            if (doneByDate.getOrDefault(d.date(), Set.of()).contains(d.action().name())) {
                continue;
            }
            PlanTask t = new PlanTask();
            t.setPlanDate(d.date());
            t.setModule(d.action().module());
            t.setAction(d.action().name());
            t.setVariant(d.variant());
            t.setTask(cut(d.title(), 255));
            t.setDetails(cut(d.why(), 2000));
            t.setMinutes(d.minutes());
            t.setPriority(d.priority());
            t.setSource(source);
            t.setWeekStart(from);
            t.setCreatedAt(now);
            tasks.save(t);
        }
    }

    private void saveMeta(LocalDate from, int days, PlanGenerator.Phase phase, String focus, String source) {
        PlanMeta m = new PlanMeta();
        m.setStartDate(from);
        m.setEndDate(from.plusDays(days - 1));
        m.setPhase(phase.name());
        m.setFocus(cut(focus, 4000));
        m.setSource(source);
        m.setGeneratedAt(Instant.now(clock));
        metas.save(m);
    }

    // ------------------------------------------------------------------ auto-completion

    /** Ticks off today's tasks that a completed session (or enough vocabulary reviews) already covers. */
    void autoComplete(LocalDate day) {
        List<PlanTask> open = tasks.findByPlanDateBetweenOrderByPlanDateAscPriorityAscIdAsc(day, day).stream()
                .filter(t -> !t.isDone()).toList();
        if (open.isEmpty()) {
            return;
        }
        ZoneId zone = clock.getZone();
        Instant start = day.atStartOfDay(zone).toInstant();
        Instant end = day.plusDays(1).atStartOfDay(zone).toInstant();
        List<PracticeSession> finished = sessions.findByStartedAtGreaterThanEqualOrderByStartedAtAsc(start.minus(Duration.ofDays(1))).stream()
                .filter(s -> s.getStatus() == SessionStatus.COMPLETED && s.getFinishedAt() != null && !s.getFinishedAt().isBefore(start)
                        && s.getFinishedAt().isBefore(end))
                .toList();
        Set<Long> used = new HashSet<>();
        for (PlanTask t : open) {
            PlanAction action;
            try {
                action = PlanAction.valueOf(t.getAction());
            } catch (RuntimeException e) {
                continue;
            }
            if (action == PlanAction.VOCAB_REVIEW) {
                long reviews = vocabReviews.countByReviewedAtBetween(start, end);
                long due = vocabCards.countBySuspendedFalseAndDueAtLessThanEqual(Instant.now(clock));
                if (reviews >= 10 || (reviews > 0 && due == 0)) {
                    t.setDone(true);
                    t.setDoneAt(Instant.now(clock));
                }
                continue;
            }
            if (action == PlanAction.MOCK_TEST) {
                finished.stream().filter(s -> s.getMockTestId() != null && s.getKind() == SessionKind.SPEAKING_TEST).findFirst()
                        .ifPresent(s -> {
                            t.setDone(true);
                            t.setDoneAt(s.getFinishedAt());
                        });
                continue;
            }
            finished.stream().filter(s -> !used.contains(s.getId()) && action.completedBy().contains(s.getKind())).findFirst()
                    .ifPresent(s -> {
                        used.add(s.getId());
                        t.setDone(true);
                        t.setDoneAt(s.getFinishedAt());
                    });
        }
    }

    // ------------------------------------------------------------------ inputs

    public PlanInputs inputs(LocalDate today) {
        UserSettings s = settings.get();
        DashboardView dash = dashboard.dashboard();
        Map<String, Double> bands = new LinkedHashMap<>();
        bands.put("LISTENING", dash.current().listening());
        bands.put("READING", dash.current().reading());
        bands.put("WRITING", dash.current().writing());
        bands.put("SPEAKING", dash.current().speaking());
        List<PlanInputs.WeakSpot> weak = dash.questionTypes().stream().filter(q -> q.total() >= 3 && q.accuracy() < 0.8)
                .sorted(Comparator.comparingDouble(q -> q.recentAccuracy() == null ? q.accuracy() : q.recentAccuracy()))
                .limit(6).map(q -> new PlanInputs.WeakSpot(q.module(), q.questionType(), q.accuracy(), q.total())).toList();
        GrammarDtos.Overview g = grammar.overview();
        List<PlanInputs.ErrorFocus> errors = g.errorPatterns().stream().filter(e -> !e.resolved()).limit(3)
                .map(e -> new PlanInputs.ErrorFocus(e.subtype(), e.area(), e.total(), e.trend())).toList();
        List<PlanInputs.AreaFocus> areas = g.areas().stream()
                .sorted(Comparator.comparing((GrammarDtos.AreaSummary a) -> !a.recommended())
                        .thenComparingDouble(a -> a.proficiency() == null ? 101 : a.proficiency()))
                .limit(3).map(a -> new PlanInputs.AreaFocus(a.key(), a.name(), a.proficiency())).toList();
        Instant now = Instant.now(clock);
        List<PracticeSession> recent = sessions.findByStartedAtGreaterThanEqualOrderByStartedAtAsc(now.minus(Duration.ofDays(7)));
        Map<String, Integer> last7 = new LinkedHashMap<>();
        recent.stream().filter(x -> x.getStatus() == SessionStatus.COMPLETED).forEach(x -> last7.merge(x.getModule().name(), 1, Integer::sum));
        Integer daysSinceMock = sessions.findByStatusOrderByStartedAtAsc(SessionStatus.COMPLETED).stream()
                .filter(x -> x.getMockTestId() != null && x.getFinishedAt() != null).map(PracticeSession::getFinishedAt)
                .max(Instant::compareTo).map(t -> (int) ChronoUnit.DAYS.between(t.atZone(clock.getZone()).toLocalDate(), today)).orElse(null);
        List<String> priorities = coachReports.findFirstByOrderByCreatedAtDescIdDesc()
                .map(r -> Json.read(r.getReport(), CoachReportContent.class))
                .map(c -> c.priorities() == null ? List.<String>of() : c.priorities().stream().map(p -> p.module() + ": " + p.title() + " — " + p.detail()).toList())
                .orElse(List.of());
        int daily = s.getDailyStudyMinutes() > 0 ? s.getDailyStudyMinutes() : 90;
        return new PlanInputs(today, s.getTestDate(), s.getTargetBand().doubleValue(), s.getCurrentBand().doubleValue(), bands, daily, weak,
                errors, areas, g.diagnosticDone(), vocabCards.countBySuspendedFalseAndDueAtLessThanEqual(now), vocabCards.countBySuspendedFalse(),
                last7, daysSinceMock, recentCriteria(dash.criteriaHistory().get("WRITING")), recentCriteria(dash.criteriaHistory().get("SPEAKING")),
                priorities);
    }

    /** Average of each criterion over the three most recent graded pieces (0 = not assessed, ignored). */
    static Map<String, Double> recentCriteria(List<CriteriaPoint> points) {
        if (points == null || points.isEmpty()) {
            return Map.of();
        }
        List<CriteriaPoint> last = points.subList(Math.max(0, points.size() - 3), points.size());
        Map<String, List<Integer>> values = new LinkedHashMap<>();
        last.forEach(p -> p.bands().forEach((k, v) -> {
            if (v != null && v > 0) {
                values.computeIfAbsent(k, x -> new ArrayList<>()).add(v);
            }
        }));
        Map<String, Double> out = new LinkedHashMap<>();
        values.forEach((k, v) -> out.put(k, Math.round(v.stream().mapToInt(Integer::intValue).average().orElse(0) * 10) / 10.0));
        return out;
    }

    private static String cut(String s, int max) {
        return s == null || s.length() <= max ? s : s.substring(0, max);
    }
}
