package com.ieltsprep.session;

public enum SessionKind {
    READING_TEST,
    READING_PASSAGE,
    LISTENING_TEST,
    LISTENING_SECTION,
    WRITING_TASK1,
    WRITING_TASK2,
    WRITING_TEST,
    SPEAKING_TEST,
    SPEAKING_PART,
    GRAMMAR_DIAGNOSTIC,
    GRAMMAR_EXERCISE,
    GRAMMAR_ERROR_DRILL,
    VOCAB_REVIEW
}
